### ISSUE TITLE
Plugin will fail 2020-09-01: Needs URL change

### ISSUE THREAD

**Issue by elerch** [metiis/hooktube-redirect#18]
invidio.us will shut down on September 1st. See https://omar.yt/posts/stepping-away-from-open-source

**Comment by torresjrjr** [comment]
BUMP

It's 1st September and the canonical site invidio.us does not host the service anymore. However, if you try to go to an Invidio.us video link, the server will return a page with a list other Invidious-server video links, so it's not that bad, although bothersome to have to click a link.

I propose we add 3 options to a plugin to redirect YouTube links to either a preferred Invidious site, a random one, or a default one.

**Comment by metiis** [comment]
Sorry for the late reply, I hadn't looked into the email account in a while. I just merged #19, will upload the new version in a bit.
