### ISSUE TITLE
Youtube video links redirect to the same video

### ISSUE THREAD

**Issue by theonetoday** [metiis/hooktube-redirect#2]
Every video link I open redirects to the same video.

**Comment by metiis** [comment]
Which video does it redirect to? It might be a problem with HookTube, my extension only changes the "youtube.com" part of the URL to "hooktube.com", it doesn't modify the part defining the video.

**Comment by theonetoday** [comment]
It links to a YouTube video I had watched previously. I actually don't think its an issue with your extension now. I believe it has something to do with Firefox although I haven't been able to figure it out even after completely wiping it along with all of my userdata. You can close the issue though as this seems unrelated. Thanks
