### ISSUE TITLE
Add ability to configure invidious url/domain

### ISSUE THREAD

**Issue by Perflyst** [metiis/hooktube-redirect#6]
Please add the ability to change the invidious instance domain. For example someone wants to use anothers instance or his own private one.

**Comment by kaffeeringe** [comment]
Yes! The German instance at invidious.enkirton.net is way faster for me than the US-version.

**Comment by Perflyst** [comment]
The addon seems kinda dead, I would suggest using https://addons.mozilla.org/en-US/firefox/addon/invidition/ instead

**Comment by doronbehar** [comment]
Or my fork: https://github.com/doronbehar/invidious-redirect

**Comment by metiis** [comment]
#19 introduces this, finally. Sorry for the long silence, I kinda forgot about this addon.
